part1:
	g++ -std=c++11 -o part1 part1.cpp Dealership.cpp Showroom.cpp Vehicle.cpp && ./part1
part2:
	g++ -std=c++11 -o part2 part2.cpp Dealership.cpp Showroom.cpp Vehicle.cpp && ./part2
part3:
	g++ -std=c++11 -o part3 part3.cpp Dealership.cpp Showroom.cpp Vehicle.cpp && ./part3
